name: CI/CD Pipeline

on:
  push:
    branches: [ main ]    # Run when code is pushed to 'main'
  pull_request:
    branches: [ main ]    # Also run for PRs to 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3     # Pull your repo files into the runner

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest
